language: python
python:
  - 2.7
notifications:
  email: false
install:
  - pip install -r requirements.txt
before_script:
  - cp mothra/__local_settings.py mothra/local_settings.py
script:
  - python manage.py test
